# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLfKTn-pQZqLcLzFfcq3ObtN0hds_wgn
"""

!pip install streamlit

import pandas as pd
import streamlit as st
import random

# Example CSV: english,tamil
data = pd.DataFrame({
    "english": ["Good morning", "Thank you", "Where is the bus stop?"],
    "tamil": ["காலை வணக்கம்", "நன்றி", "பஸ் நிறுத்தம் எங்கே?"]
})

st.title("Learn Tamil Chatbot")
idx = random.randint(0, len(data) - 1)
st.write("Translate this:", data['english'][idx])

if st.button("Show Answer"):
    st.success(data['tamil'][idx])